const types = {
    ADMIN_GET_USERS: 'ADMIN_GET_USERS',
    ADMIN_CHANGE_ROLE: 'ADMIN_CHANGE_ROLE',
    ADMIN_COURSE_CHANGE_ROLE: 'ADMIN_COURSE_CHANGE_ROLE',
    ADMIN_ADD_TO_COURSE: 'ADMIN_ADD_TO_COURSE',
    ADMIN_DELETE_ROLE: 'ADMIN_DELETE_ROLE',
    ADMIN_RESET: 'ADMIN_RESET',

    COURSE_GET_DATA: 'COURSE_GET_DATA',
    COURSE_GET_MATRIX: 'COURSE_GET_MATRIX',
    COURSE_RESET: 'COURSE_RESET',

    CATEGORY_CREATE: 'CATEGORY_CREATE',
    CATEGORY_DELETE: 'CATEGORY_DELETE',
    CATEGORY_EDIT: 'CATEGORY_EDIT',

    OBJECTIVE_CREATE: 'OBJECTIVE_CREATE',
    OBJECTIVE_DELETE: 'OBJECTIVE_DELETE',
    OBJECTIVE_EDIT: 'OBJECTIVE_EDIT',

    LEVEL_CREATE: 'LEVEL_CREATE',
    LEVEL_DELETE: 'LEVEL_DELETE',
    LEVEL_EDIT: 'LEVEL_EDIT',

    TASK_CHANGE_ACTIVE: 'TASK_CHANGE_ACTIVE',
    TASK_CREATE: 'TASK_CREATE',
    TASK_DELETE: 'TASK_DELETE',
    TASK_ATTACH_OBJECTIVE: 'TASK_ATTACH_OBJECTIVE',
    TASK_DETACH_OBJECTIVE: 'TASK_DETACH_OBJECTIVE',
    TASK_ATTACH_TYPE: 'TASK_ATTACH_TYPE',
    TASK_DETACH_TYPE: 'TASK_DETACH_TYPE',
    TASK_EDIT: 'TASK_EDIT',
    TASK_EDIT_OBJECTIVE_MULTIPLIERS: 'TASK_EDIT_OBJECTIVE_MULTIPLIERS',

    TYPE_EDIT: 'TYPE_EDIT',
    TYPE_DELETE: 'TYPE_DELETE',
    TYPE_CREATE: 'TYPE_CREATE',
    TYPE_HEADER_CREATE: 'TYPE_HEADER_CREATE',
    TYPE_HEADER_DELETE: 'TYPE_HEADER_DELETE',
    TYPE_HEADER_EDIT: 'TYPE_HEADER_EDIT',

    RESET_ERROR: 'RESET_ERROR',

    GRADE_GET_MANY: 'GRADE_GET_MANY',
    GRADE_CREATE: 'GRADE_CREATE',
    GRADE_DELETE: 'GRADE_DELETE',
    GRADE_EDIT: 'GRADE_EDIT',
    GRADE_UPDATE_CATEGORY_GRADES_ATTEMPT:
        'GRADE_UPDATE_CATEGORY_GRADES_ATTEMPT',
    GRADE_UPDATE_CATEGORY_GRADES_SUCCESS:
        'GRADE_UPDATE_CATEGORY_GRADES_SUCCESS',
    GRADE_UPDATE_CATEGORY_GRADES_FAILURE:
        'GRADE_UPDATE_CATEGORY_GRADES_FAILURE',

    COURSES_GET_INSTANCE_DATA_ATTEMPT: 'COURSES_GET_INSTANCE_DATA_ATTEMPT',
    COURSES_GET_INSTANCE_DATA_SUCCESS: 'COURSES_GET_INSTANCE_DATA_SUCCESS',
    COURSES_GET_INSTANCE_DATA_FAILURE: 'COURSES_GET_INSTANCE_DATA_FAILURE',
    COURSES_GET_INSTANCE_TASKS_ATTEMPT: 'COURSES_GET_INSTANCE_TASKS_ATTEMPT',
    COURSES_GET_INSTANCE_TASKS_SUCCESS: 'COURSES_GET_INSTANCE_TASKS_SUCCESS',
    COURSES_GET_INSTANCE_TASKS_FAILURE: 'COURSES_GET_INSTANCE_TASKS_FAILURE',
    COURSE_INSTANCE_RESET: 'COURSE_INSTANCE_RESET',
    COURSE_EDIT: 'COURSE_EDIT',
    ASSESMENT_RESPONSE_CREATE_ATTEMPT: 'ASSESMENT_RESPONSE_CREATE_ATTEMPT',
    ASSESMENT_RESPONSE_CREATE_SUCCESS: 'ASSESMENT_RESPONSE_CREATE_SUCCESS',
    ASSESMENT_RESPONSE_CREATE_FAILURE: 'ASSESMENT_RESPONSE_CREATE_FAILURE',
    CREATE_SELF_ASSESMENT_ATTEMPT: 'CREATE_SELF_ASSESMENT_ATTEMPT',
    CREATE_SELF_ASSESMENT_SUCCESS: 'CREATE_SELF_ASSESMENT_SUCCESS',
    CREATE_SELF_ASSESMENT_FAILURE: 'CREATE_SELF_ASSESMENT_FAILURE',
    SELF_ASSESSMENT_TOGGLE_ATTEMPT: 'SELF_ASSESSMENT_TOGGLE_ATTEMPT',
    SELF_ASSESSMENT_TOGGLE_SUCCESS: 'SELF_ASSESSMENT_TOGGLE_SUCCESS',
    SELF_ASSESSMENT_TOGGLE_FAILURE: 'SELF_ASSESSMENT_TOGGLE_FAILURE',
    SELF_ASSESSMENT_STATUS_ATTEMPT: 'SELF_ASSESSMENT_STATUS_ATTEMPT',
    SELF_ASSESSMENT_STATUS_SUCCESS: 'SELF_ASSESSMENT_STATUS_SUCCESS',
    SELF_ASSESSMENT_STATUS_FAILURE: 'SELF_ASSESSMENT_STATUS_FAILURE',
    COURSE_INSTANCE_TOGGLE_ACTIVITY_ATTEMPT:
        'COURSE_INSTANCE_TOGGLE_ACTIVITY_ATTEMPT',
    COURSE_INSTANCE_TOGGLE_ACTIVITY_SUCCESS:
        'COURSE_INSTANCE_TOGGLE_ACTIVITY_SUCCESS',
    COURSE_INSTANCE_TOGGLE_ACTIVITY_FAILURE:
        'COURSE_INSTANCE_TOGGLE_ACTIVITY_FAILURE',
    COURSE_INSTANCE_UPDATE_PERSON_ATTEMPT:
        'COURSE_INSTANCE_UPDATE_PERSON_ATTEMPT',
    COURSE_INSTANCE_UPDATE_PERSON_SUCCESS:
        'COURSE_INSTANCE_UPDATE_PERSON_SUCCESS',
    COURSE_INSTANCE_UPDATE_PERSON_FAILURE:
        'COURSE_INSTANCE_UPDATE_PERSON_FAILURE',
    COURSE_INSTANCE_POST_TASK_RESPONSES_ATTEMPT:
        'COURSE_INSTANCE_POST_TASK_RESPONSES_ATTEMPT',
    COURSE_INSTANCE_POST_TASK_RESPONSES_SUCCESS:
        'COURSE_INSTANCE_POST_TASK_RESPONSES_SUCCESS',
    COURSE_INSTANCE_POST_TASK_RESPONSES_FAILURE:
        'COURSE_INSTANCE_POST_TASK_RESPONSES_FAILURE',
    COURSE_INSTANCE_DELETE_PERSON_ATTEMPT:
        'COURSE_INSTANCE_DELETE_PERSON_ATTEMPT',
    COURSE_INSTANCE_DELETE_PERSON_SUCCESS:
        'COURSE_INSTANCE_DELETE_PERSON_SUCCESS',
    COURSE_INSTANCE_DELETE_PERSON_FAILURE:
        'COURSE_INSTANCE_DELETE_PERSON_FAILURE',

    COURSELIST_GET_TEMPLATE_INSTANCES: 'COURSELIST_GET_TEMPLATE_INSTANCES',
    COURSELIST_GET_COURSES: 'COURSELIST_GET_COURSES',
    COURSELIST_GET_INSTANCES: 'COURSELIST_GET_INSTANCES',
    COURSELIST_COURSE_SELECT: 'COURSELIST_COURSE_SELECT',
    COURSELIST_INSTANCE_SELECT: 'COURSELIST_INSTANCE_SELECT',
    COURSELIST_INSTANCE_CREATE: 'COURSELIST_INSTANCE_CREATE',
    COURSELIST_INSTANCE_EDIT: 'COURSELIST_INSTANCE_EDIT',
    COURSELIST_REGISTER: 'COURSELIST_REGISTER',
    COURSELIST_UNREGISTER: 'COURSELIST_UNREGISTER',
    COURSE_CREATE: 'COURSE_CREATE',

    INIT_NEW_FORM: 'INIT_NEW_FORM',
    GET_SELF_ASSESMENT_ATTEMPT: 'GET_SELF_ASSESMENT_ATTEMPT',
    GET_SELF_ASSESMENT_SUCCESS: 'GET_SELF_ASSESMENT_SUCCESS',
    GET_SELF_ASSESMENT_FAILURE: 'GET_SELF_ASSESMENT_FAILURE',
    GET_ASSESMENT_RESPONSE_ATTEMPT: 'GET_ASSESMENT_RESPONSE_ATTEMPT',
    GET_ASSESMENT_RESPONSE_SUCCESS: 'GET_ASSESMENT_RESPONSE_SUCCESS',
    GET_ASSESMENT_RESPONSE_FAILURE: 'GET_ASSESMENT_RESPONSE_FAILURE',
    OPEN_QUESTION_RESPONSE: 'OPEN_QUESTION_RESPONSE',
    GRADE_CATEGORY_RESPONSE: 'GRADE_CATEGORY_RESPONSE',
    GRADE_OBJECTIVE_RESPONSE: 'GRADE_OBJECTIVE_RESPONSE',
    TEXTFIELD_RESPONSE: 'TEXTFIELD_RESPONSE',
    TOGGLE_TEXT_FIELD: 'TOGGLE_TEXT_FIELD',
    TOGGLE_DOWN: 'TOGGLE_DOWN',
    TOGGLE_UP: 'TOGGLE_UP',
    ADD_OPEN_QUESTION: 'ADD_OPEN_QUESTION',
    REMOVE_OPEN_QUESTION: 'REMOVE_OPEN_QUESTION',
    CHANGE_TEXT_FIELD: 'CHANGE_TEXT_FIELD',
    TOGGLE_FORM_PART: 'TOGGLE_FORM_PART',
    CHANGE_HEADER: 'CHANGE_HEADER',
    GET_ALL_USER_SELFASSESMENTS_ATTEMPT: 'GET_ALL_USER_SELFASSESMENTS_ATTEMPT',
    GET_ALL_USER_SELFASSESMENTS_SUCCESS: 'GET_ALL_USER_SELFASSESMENTS_SUCCESS',
    GET_ALL_USER_SELFASSESMENTS_FALURE: 'GET_ALL_USER_SELFASSESMENTS_FALURE',
    SELF_ASSESMENT_UPDATE_ATTEMPT: 'SELF_ASSESMENT_UPDATE_ATTEMPT',
    SELF_ASSESMENT_UPDATE_SUCCESS: 'SELF_ASSESMENT_UPDATE_SUCCESS',
    SELF_ASSESMENT_UPDATE_FAILURE: 'SELF_ASSESMENT_UPDATE_FAILURE',
    CLEAR_ASSESSMENT: 'CLEAR_ASSESSMENT',

    SELF_ASSESMENT_LIST_INIT: 'SELF_ASSESMENT_LIST_INIT',
    SELF_ASSESMENT_LIST_RESET: 'SELF_ASSESMENT_LIST_RESET',
    SELF_ASSESMENT_LIST_SELECT_RESPONSE: 'SELF_ASSESMENT_LIST_SELECT_RESPONSE',
    SELF_ASSESMENT_LIST_ACTIVATE_RESPONSE:
        'SELF_ASSESMENT_LIST_ACTIVATE_RESPONSE',
    SELF_ASSESMENT_LIST_SELECT_ALL: 'SELF_ASSESMENT_LIST_SELECT_ALL',
    SELF_ASSESMENT_LIST_DESELECT_ALL: 'SELF_ASSESMENT_LIST_DESELECT_ALL',
    SELF_ASSESMENT_LIST_REGENERATE: 'SELF_ASSESMENT_LIST_REGENERATE',
    SELF_ASSESMENT_DELETE: 'SELF_ASSESMENT_DELETE',

    USER_GET_ATTEMPT: 'USER_GET_ATTEMPT',
    USER_GET_SUCCESS: 'USER_GET_SUCCESS',
    USER_GET_FAILURE: 'USER_GET_FAILURE',
    USER_LOGIN_ATTEMPT: 'USER_LOGIN_ATTEMPT',
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAILURE: 'USER_LOGIN_FAILURE',
    USER_LOGOUT: 'USER_LOGOUT',

    USER_GET_COURSES_ATTEMPT: 'USER_GET_COURSES_ATTEMPT',
    USER_GET_COURSES_SUCCESS: 'USER_GET_COURSES_SUCCESS',
    USER_GET_COURSES_FAILURE: 'USER_GET_COURSES_FAILURE',

    VALIDATE_RESPONSE: 'VALIDATE_RESPONSE',
    CLEAR_RESPONSE_ERROR: 'CLEAR_RESPONSE_ERROR',
    CLEAR_VALIDATION: 'CLEAR_VALIDATION',
    CLOSE_MODAL: 'CLOSE_MODAL',
}
export default types
